Hotfix elim rotation
maxkapur/assignment pull request #2
Opened 2022-08-23 02:41 UTC by takemi853

This patch fix is the bug on elimination target pointing.

2022-08-24 04:24 UTC, maxkapur requested changes
Thanks for the PR! Just a few minor issues:
- Please remove the cached binary files `__pycache__/maxflow.cpython-39.pyc` and `__pycache__/maxflow.cpython-39.pyc` (I should have put these in `.gitignore` at the outset)
- Small typo `rotaion` in a comment

2022-08-24 04:24 UTC, maxkapur commented on assignment.py
> +        # Remove p (anyone same or worse than rotaion[i]) from r's list
```suggestion
        # Remove p (anyone same or worse than rotation[i]) from r's list
```

2022-08-25 00:28 UTC, takemi853 commented
I removed the files and fixed the typo!

2022-08-25 02:18 UTC, maxkapur commented
Looks great, thank you!

2022-08-25 02:19 UTC, merged